apiVersion: v1
kind: Pod

metadata:
  name: mypod
  labels:
    env: dev
    status: xyz
    team: prod

spec:
  containers:
    - name: bala
      image: nginx
      ports:
        - containerPort: 80