apiVersion: v1
kind: Pod

metadata:
  name: testnspod
  # namespace: test
  labels:
    app: myapp

spec:
  containers:
    - name: bala
      image: nginx
      env:
        - name: myName
          value: gaurav
        - name: myCity
          value: pune
      ports:
        - containerPort: 80