apiVersion: v1
kind: Pod

metadata:
  name: testnspod3
  # namespace: test
  labels:
    app: myapp

spec:
  containers:
    - name: bala
      image: nginx
      resources:
        requests:
          memory: 250Mi
          cpu: 0.1
        limits:
          memory: 0.5
          cpu: 500Mi
      env:
        - name: myName
          value: gaurav
        - name: myCity
          value: pune
      ports:
        - containerPort: 80