apiVersion: v1
kind: Pod

metadata:
  name: testnspod5
  # namespace: test
  labels:
    app: myapp

spec:
  containers:
    - name: bala
      image: nginx
      resources:
        requests:
          memory: 100Mi
      #   cpu: 100m
        limits:
          memory: 1000Mi
      #  cpu: 500m
      env:
        - name: myName
          value: gaurav
        - name: myCity
          value: pune
      ports:
        - containerPort: 80