apiVersion: v1
kind: Pod

metadata:
  name: mypod2
  labels:
    app: myapp1
    type: backend

spec:
  containers:
    - name: bala
      image: httpd
      env:
        - name: myName
          value: gaurav
        - name: myCity
          value: pune
      ports:
        - containerPort: 80