apiVersion: v1
kind: ReplicationController

metadata:
  name: firstrc
  labels:
    appname: myapp

spec:
  replicas: 5
  template:
    metadata:
      name: firstpod
      labels:
        type: app
    spec:
      containers:
        - name: firstcontainer
          image: nginx