apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: firstrc
  labels:
    name: firstrc

spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - myapp1
          - myapp2

  template:
    metadata:
      name: pod
      labels:
        app: myapp1
    spec:
      containers:
        - name: container
          image: nginx